//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationAndManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetweenStation
    {
        public int BetweenStationID { get; set; }
        public int TrainID { get; set; }
        public int StationID { get; set; }
        public int OridinalNumber { get; set; }
        public int Distances { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual TrainSchedule TrainSchedule { get; set; }
    }
}
