//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationAndManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int ReservationID { get; set; }
        public Nullable<int> CancelNo { get; set; }
        public int PNRID { get; set; }
        public int Status { get; set; }
        public decimal CancellationFees { get; set; }
    
        public virtual CancellationRule CancellationRule { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
