//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationAndManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbRailwayReservationAndManagementSystemEntities13 : DbContext
    {
        public dbRailwayReservationAndManagementSystemEntities13()
            : base("name=dbRailwayReservationAndManagementSystemEntities13")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BetweenStation> BetweenStations { get; set; }
        public virtual DbSet<Cancellation> Cancellations { get; set; }
        public virtual DbSet<CancellationRule> CancellationRules { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<TrainSchedule> TrainSchedules { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
