//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationAndManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public int PNRID { get; set; }
        public int TrainID { get; set; }
        public System.DateTime DateOfTravel { get; set; }
        public string Name { get; set; }
        public string StartStationCode { get; set; }
        public string EndStationCode { get; set; }
        public int CoachNo { get; set; }
        public string ClassID { get; set; }
        public int TotalPassenger { get; set; }
        public int SeatNo { get; set; }
        public decimal TotalFee { get; set; }
        public System.DateTime ReservateDate { get; set; }
    
        public virtual Cancellation Cancellation { get; set; }
        public virtual Class Class { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Train Train { get; set; }
    }
}
