//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationAndManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Train()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int TrainID { get; set; }
        public int TrainNo { get; set; }
        public string TrainName { get; set; }
        public string RouteFromTo { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public int NoOfCoach { get; set; }
        public int NoOfCompartment { get; set; }
        public int C1AC { get; set; }
        public int C2AC { get; set; }
        public int C3AC { get; set; }
        public int Sleeper { get; set; }
        public int General { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual TrainSchedule TrainSchedule { get; set; }
    }
}
